# eureka by default will register itself as a client. So, we need to set it to false.
# What's a client server? See other microservices (image, gallery, auth, etc).
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
# eureka server port
server:
  port: ${EUREKA_SERVER_PORT:8761}