server:
  port: ${SERVER_PORT:8080}

spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak-oauth}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${EUREKA_HOST:localhost}:${KEYCLOAK_SERVER_PORT:8484}/auth/realms/my_realm
        registration:
          keycloak:
            client-id: my_client
#            client-id: service_client
            client-secret: UEtvymOPqsE23YHPQy9PLm9X9k1Q8XlI