server:
  port: ${SERVER_PORT:8080}

spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak}
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:keycloak_db}
    username: ${DB_USERNAME:-postgres}
    password: ${DB_PASSWORD:-postgres}
    driverClassName: org.postgresql.Driver

keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: my_realm
  resource: my_client
  public-client: true

