version: "3.8"

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    volumes:
      - ./backend/keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
#      - ./keycloak/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "app.py"]

  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER:-postgres@ya.ru}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_USER:-postgres}
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
      - keycloak
    command: ["./wait-for-it.sh", "keycloak:8080", "--", "python", "app.py"]
    command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "app.py"]
    
  config:
    build: 
      context: .
      dockerfile: docker/config.Dockerfile
    container_name: 'config'
    ports:
      - '8888:8888'
    restart: unless-stopped
    depends_on:
      - keycloak 
    command: ["./wait-for-it.sh", "keycloak:8080", "--", "python", "app.py"]
    
  eureka:
    build: 
      context: .
      dockerfile: docker/eureka.Dockerfile
    container_name: 'eureka'
    ports:
      - '8761:8761'
    restart: unless-stopped
    depends_on:
      - config  
    command: ["./wait-for-it.sh", "config:8888", "--", "python", "app.py"]
    
  gateway:
    build: 
      context: .
      dockerfile: docker/gateway.Dockerfile
    container_name: 'gateway'
    ports:
      - '9090:9090'
    restart: unless-stopped
    depends_on:
      - eureka
    command: ["./wait-for-it.sh", "eureka:9090", "--", "python", "app.py"]
      
  resource:
    build: 
      context: .
      dockerfile: docker/resource.Dockerfile
    container_name: 'resource'
    ports:
      - '9191:9191'
    restart: unless-stopped
    depends_on:
      - eureka
    command: ["./wait-for-it.sh", "eureka:9090", "--", "python", "app.py"]
      
