spring:
  cloud:
    config:
      import: configserver:http://${EUREKA_HOST:localhost}:${CONFIG_SERVER_PORT:8888}/eureka/

  application:
    name: keycloak-resource

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/realm/protocol/openid-connect/certs
server:
  port: ${SERVER_PORT:9191}
