# all modules extend default config

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DNS_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    prefer-same-zone-eureka: true
    region: region-1
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

# Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG