# eureka by default will register itself as a client. So, we need to set it to false.

server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: service_client
            client-secret: 4FSL9OHsJEst5j9pNPMbtgrSJaNxnygc