spring:
  application:
    name: keycloak-resource
  cloud:
    config:
      import: configserver:http://${EUREKA_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/realm/protocol/openid-connect/certs
server:
  port: 9191
