spring:
  application:
    name: keycloak-oauth-server
  cloud:
    config:
      import: configserver:http://${EUREKA_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${EUREKA_HOST:localhost}:${KEYCLOAK_SERVER_PORT:8484}/auth/realms/my_realm
        registration:
          keycloak:
            client-id: service_client
            client-secret: UEtvymOPqsE23YHPQy9PLm9X9k1Q8XlI