server:
  port: ${SERVER_PORT:9090}

# Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
spring:
  config:
    import: optional:secrets.properties
  application:
    name: ${APPLICATION_NAME:keycloak-gateway-oauth2}
  cloud:
    config:
      import: configserver:http://${EUREKA_HOST:localhost}:${CONFIG_SERVER_PORT:8888}/eureka/
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: product-resource-server
          uri: http://${EUREKA_HOST:localhost}:9191
          predicates:
            - Path=/product/**
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/realm
            # Individual properties can also be provided this way
            token-uri: http://localhost:8080/auth/realms/realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/realm/protocol/openid-connect/auth
        #            userinfo-uri: http://localhost:8080/auth/realms/realm/protocol/openid-connect/userinfo
        #            user-name-attribute: preferred_username
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: ${KEYCLOAK_CLIENT_ID:spring-gateway-client}
            client-secret: ${KEYCLOAK_SECRET:3OitJp6DxC27b93QVt8mYOBJvCZEfJ8S}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
management:
  endpoints:
    web:
      exposure:
        include: "*"